### ISSUE TITLE
DOC what does `isotropy="split"` correspond to?

### ISSUE THREAD

**Issue by mathurinm** [benchopt/benchmark_tv_2d#24]
`"split"` appears only once in the repo (in the objective) and is not referred to in the doc. To which kind of discretization does it correspond?

**Comment by svaiter** [comment]
To these two papers:
- [Chambolle, Antonin, and Thomas Pock. "A remark on accelerated block coordinate descent for computing the proximity operators of a sum of convex functions." The SMAI Journal of computational mathematics 1 (2015): 29-54.](http://www.numdam.org/article/SMAI-JCM_2015__1__29_0.pdf)
- [Chambolle, Antonin, Pauline Tan, and Samuel Vaiter. "Accelerated alternating descent methods for Dykstra-like problems." Journal of Mathematical Imaging and Vision 59 (2017): 481-497.](https://hal.science/hal-01346532/file/AlterDescent2.pdf)

This is an alternative discretisation of the continuous 2D TV friendly to GPU computation. I should provide an implementation in the future, but we could remove the option for the moment.

**Comment by svaiter** [comment]
To these two papers:
- [Chambolle, Antonin, and Thomas Pock. "A remark on accelerated block coordinate descent for computing the proximity operators of a sum of convex functions." The SMAI Journal of computational mathematics 1 (2015): 29-54.](http://www.numdam.org/article/SMAI-JCM_2015__1__29_0.pdf)
- [Chambolle, Antonin, Pauline Tan, and Samuel Vaiter. "Accelerated alternating descent methods for Dykstra-like problems." Journal of Mathematical Imaging and Vision 59 (2017): 481-497.](https://hal.science/hal-01346532/file/AlterDescent2.pdf)

This is an alternative discretisation of the continuous 2D TV friendly to GPU computation. I should provide an implementation in the future, but we could remove the option for the moment.

**Comment by mathurinm** [comment]
Thanks for the fast answer! Since it's not used at the moment I'll remove it for now and open an issue to keep track of the potential additions
